# Generated by Django 4.1.3 on 2023-09-24 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='uuid',
            new_name='chatname',
        ),
    ]
