# Generated by Django 4.1.3 on 2023-09-24 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_uuid_group_chatname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='chatname',
            new_name='uuid',
        ),
    ]
