# Generated by Django 4.1.3 on 2023-09-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_group_chatname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='chatname',
            field=models.CharField(max_length=50),
        ),
    ]
