# Generated by Django 3.2.22 on 2023-10-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_group_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
