# Generated by Django 3.2.22 on 2023-11-12 11:09

from django.db import migrations


def add_chats(apps, schema_editor):
    # We can't import Group model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Chat = apps.get_model("chat", "Group")

    Chat.objects.get_or_create(chatname='Sport')
    Chat.objects.get_or_create(chatname='Games')
    Chat.objects.get_or_create(chatname='Films')
    Chat.objects.get_or_create(chatname='Travel')
    Chat.objects.get_or_create(chatname='Music')
    Chat.objects.get_or_create(chatname='Education')
    Chat.objects.get_or_create(chatname='Cooking')


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_message_timestamp'),
    ]

    operations = [
        migrations.RunPython(add_chats),
    ]
