# Generated by Django 3.2.22 on 2023-11-12 12:39

from django.db import migrations
from datetime import datetime


created_time = datetime.now().replace(microsecond=0)

def add_messages(apps, schema_editor):
    # We can't import Group model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Message = apps.get_model("chat", "Message")
    Member = apps.get_model("members", "Members")
    Chat = apps.get_model("chat", "Group")

    Message.objects.get_or_create(author=Member.objects.get(user_id=1), timestamp=created_time, content="Hello Sport chat", group=Chat.objects.get(id=1))
    Message.objects.get_or_create(author=Member.objects.get(user_id=2), timestamp=created_time, content="Hello Sport chat one more time", group=Chat.objects.get(id=1))
    Message.objects.get_or_create(author=Member.objects.get(user_id=2), timestamp=created_time, content="Hello Games chat", group=Chat.objects.get(id=2))
    Message.objects.get_or_create(author=Member.objects.get(user_id=3), timestamp=created_time, content="Hello Sport chat", group=Chat.objects.get(id=3))


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20231112_1309'),
    ]

    operations = [
        migrations.RunPython(add_messages),
    ]
